import { mkdir, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import {
  alerts,
  cabinProducts,
  catchPhotos,
  catches,
  contactInfo,
  lakeClosures,
  lakes,
  mapFacilities,
  mapLayers,
  mapShapes,
  pegs,
  placeIssues,
  paymentMethods,
  permitProducts,
  rentalBookings,
  rentalItems,
  requiredEquipment,
  reservationExtras,
  reservations,
  sponsors,
  tournamentCatches,
  tournamentMarshals,
  tournamentPenalties,
  tournamentRequests,
  tournamentRuleChecks,
  tournaments,
  tripLogbookEntries,
  tripLogbooks,
} from '../app/data/pond.ts'
import {
  buildSupabaseSeedPayload,
  validateSupabaseSeedPayload,
} from '../app/services/supabaseSeedService.ts'

const jsonOutputPath = resolve('supabase', 'seed', 'rybolov-cetin.seed.json')
const sqlOutputPath = resolve('supabase', 'seed.sql')
const generatedAt = process.env.SEED_GENERATED_AT ?? '2026-05-17T00:00:00.000Z'
const tableInsertOrder = [
  'venues',
  'lakes',
  'pegs',
  'map_layers',
  'map_facilities',
  'place_issues',
  'permit_products',
  'cabin_products',
  'cabin_product_pegs',
  'required_equipment_items',
  'rental_items',
  'reservation_extras',
  'payment_methods',
  'reservations',
  'reservation_items',
  'rental_bookings',
  'lake_closures',
  'lake_closure_pegs',
  'alerts',
  'catch_records',
  'catch_photos',
  'trip_logbooks',
  'trip_logbook_pegs',
  'trip_logbook_members',
  'trip_logbook_entries',
  'tournament_organizations',
  'tournaments',
  'tournament_sectors',
  'tournament_teams',
  'tournament_marshals',
  'tournament_marshal_sectors',
  'tournament_requests',
  'tournament_catches',
  'tournament_penalties',
  'tournament_rule_checks',
  'map_shapes',
  'sponsors',
  'sponsor_assets',
  'sponsor_placements',
] as const

function quoteIdentifier(value: string) {
  if (!/^[a-z][a-z0-9_]*$/.test(value)) {
    throw new Error(`Unsafe SQL identifier in Supabase seed: ${value}`)
  }

  return `"${value}"`
}

function buildSupabaseSeedSql(tables: Record<string, Record<string, unknown>[]>) {
  const configuredTables = new Set<string>(tableInsertOrder)
  const missingTables = Object.keys(tables).filter((table) => !configuredTables.has(table))
  if (missingTables.length > 0) {
    throw new Error(`Missing seed insert order for tables: ${missingTables.join(', ')}`)
  }

  const statements = tableInsertOrder.flatMap((table) => {
    const rows = tables[table] ?? []
    if (rows.length === 0) return []

    const columns = [...new Set(rows.flatMap((row) => Object.keys(row)))].sort()
    const quotedColumns = columns.map(quoteIdentifier).join(', ')
    const json = JSON.stringify(rows)
    if (json.includes('$seed$')) {
      throw new Error(`Seed JSON for ${table} contains the reserved SQL delimiter $seed$.`)
    }

    return [
      `insert into public.${quoteIdentifier(table)} (${quotedColumns})`,
      `select ${quotedColumns}`,
      `from jsonb_populate_recordset(null::public.${quoteIdentifier(table)}, $seed$${json}$seed$::jsonb)`,
      'on conflict do nothing;',
    ].join('\n')
  })

  return [
    '-- Generated by pnpm seed:export. Do not edit by hand.',
    'begin;',
    ...statements,
    'commit;',
    '',
  ].join('\n\n')
}
const payload = buildSupabaseSeedPayload(
  {
    alerts,
    cabinProducts,
    catchPhotos,
    catches,
    contactInfo,
    lakeClosures,
    lakes,
    mapFacilities,
    mapLayers,
    mapShapes,
    pegs,
    placeIssues,
    paymentMethods,
    permitProducts,
    rentalBookings,
    rentalItems,
    requiredEquipment,
    reservationExtras,
    reservations,
    sponsors,
    tournamentCatches,
    tournamentMarshals,
    tournamentPenalties,
    tournamentRequests,
    tournamentRuleChecks,
    tournaments,
    tripLogbookEntries,
    tripLogbooks,
  },
  {
    baseDate: '2026-05-17',
    generatedAt,
  },
)
const validation = validateSupabaseSeedPayload(payload)

if (!validation.ok) {
  console.error('Seed export validation failed:')
  for (const message of validation.messages) {
    console.error(`- ${message}`)
  }
  process.exitCode = 1
}
else {
  await mkdir(dirname(jsonOutputPath), { recursive: true })
  await writeFile(jsonOutputPath, `${JSON.stringify(payload, null, 2)}\n`, 'utf8')
  await writeFile(sqlOutputPath, buildSupabaseSeedSql(payload.tables), 'utf8')

  const totalRows = Object.values(payload.metadata.counts).reduce((sum, count) => sum + count, 0)
  console.log(`Supabase JSON seed export written to ${jsonOutputPath}`)
  console.log(`Supabase SQL seed export written to ${sqlOutputPath}`)
  console.log(`Tables: ${Object.keys(payload.tables).length}, rows: ${totalRows}`)
}
